spring.datasource.url=jdbc:mysql://avnadmin:AVNS_8xze0haTRhyANYKL_7H@mysql-3ce4389-rafa-c7c8.a.aivencloud.com:17471/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=root
spring.datasource.password=@1@senac2021

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
